version: '3.3'

services:

    app:
      build: .
      depends_on: 
        - 'database'
      environment: 
        ENV POSTGRES_PORT: 5432 
        POSTGRES_HOST: database 
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: password 
        POSTGRES_DATABASE: postgres 
        PORT: 3000
      ports: 
        - '3000:3000'
  
    database:
      build: ./database
      restart: always
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=admin
        - POSTGRES_DB=database

